class Klasifikasi {
  String bigArea;
  String smallArea;
  String kodeDpack;
  String branch;
  String shop;
  String namaDealer;
  int t1;
  int t2;
  int t3;
  int t4;
  int t5;
  int t6;
  int t7;
  int t8;
  int t9;
  int t10;
  int t11;
  int t12;
  int t13;
  int t14;
  int t15;
  int t16;
  int t17;
  int t18;
  int t19;
  int t20;
  int t21;
  int t22;
  int t23;
  int t24;
  int t25;
  int t26;
  int t27;
  int t28;
  int t29;
  int t30;
  int t31;

  Klasifikasi({
    required this.bigArea,
    required this.smallArea,
    required this.kodeDpack,
    required this.branch,
    required this.shop,
    required this.namaDealer,
    required this.t1,
    required this.t2,
    required this.t3,
    required this.t4,
    required this.t5,
    required this.t6,
    required this.t7,
    required this.t8,
    required this.t9,
    required this.t10,
    required this.t11,
    required this.t12,
    required this.t13,
    required this.t14,
    required this.t15,
    required this.t16,
    required this.t17,
    required this.t18,
    required this.t19,
    required this.t20,
    required this.t21,
    required this.t22,
    required this.t23,
    required this.t24,
    required this.t25,
    required this.t26,
    required this.t27,
    required this.t28,
    required this.t29,
    required this.t30,
    required this.t31,
  });

  factory Klasifikasi.fromJson(List<String> json) {
    return Klasifikasi(
      bigArea: json[0],
      smallArea: json[1],
      kodeDpack: json[2],
      branch: json[3],
      shop: json[4],
      namaDealer: json[5],
      t1: int.parse(json[6]),
      t2: int.parse(json[7]),
      t3: int.parse(json[8]),
      t4: int.parse(json[9]),
      t5: int.parse(json[10]),
      t6: int.parse(json[11]),
      t7: int.parse(json[12]),
      t8: int.parse(json[13]),
      t9: int.parse(json[14]),
      t10: int.parse(json[15]),
      t11: int.parse(json[16]),
      t12: int.parse(json[17]),
      t13: int.parse(json[18]),
      t14: int.parse(json[19]),
      t15: int.parse(json[20]),
      t16: int.parse(json[21]),
      t17: int.parse(json[22]),
      t18: int.parse(json[23]),
      t19: int.parse(json[24]),
      t20: int.parse(json[25]),
      t21: int.parse(json[26]),
      t22: int.parse(json[27]),
      t23: int.parse(json[28]),
      t24: int.parse(json[29]),
      t25: int.parse(json[30]),
      t26: int.parse(json[31]),
      t27: int.parse(json[32]),
      t28: int.parse(json[33]),
      t29: int.parse(json[34]),
      t30: int.parse(json[35]),
      t31: int.parse(json[36]),
    );
  }
}
